spring:
  profiles:
    active:
      - local

  application:
    name: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: "your-mail@gmail.com"
    password: "Your config"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: email-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics: "send-email"
management:
  endpoints:
    web: # Override /actuator subpath
      base-path: /
      # Configure which other endpoints to expose besides health
      exposure:
        include: health, info, metrics
